### ISSUE TITLE
Print Horner factorisation with real coefficients

### ISSUE THREAD

**Issue by johan-girardot** [MrMinimal64/multivar_horner#11]
Hi,

I would like to print the whole Horner polynomial with real coefficients (instead of c's).

This should not be too difficult but I am having some troubles dwelling into your code and your well thought but convoluted data structures.

Thank you!

**Comment by MrMinimal64** [comment]
Sorry for the late reply. I am working on it and hopefully the code will be available in the master soon. It is working in principle, but I have to make some improvements for production ready code.
Feel free to play around with the current version in the `dev` branch

**Comment by MrMinimal64** [comment]
the new version 1.3.0 supports printing the coefficients. please check the documentation for instructions. feel free to comment here.
